In [1]:
import pandas as pd

RUTA = "../../data/BASE_DATOS_VIVEROS_MAYO_2026.xlsx"

data_frame = pd.read_excel(RUTA)

In [2]:
data_frame.shape

(11295, 30)

In [3]:
data_frame.columns

Index(['No. ', 'DEPARTAMENTO', 'MUNICIPIO', 'VEREDA', 'NOMBRE DEL VIVERO',
       'LATITUD', 'LONGITUD', 'ALTITUD', 'ESTADO ',
       'NÚMERO DE REGISTRO OTORGADO ', 'FECHA DE OTORGAMIENTO DE REGISTRO',
       'VIGENCIA ', 'CAPACIDAD DE PRODUCCIÓN plantas/año', 'FRUTALES',
       'CITRICOS', 'FORESTALES', 'ORNAMENTALES', 'HORTALIZAS',
       'AROMATICAS Y MEDICINALES', 'OTRAS ESPECIES', 'PROPIETARIO NOMBRE',
       'NO. CEDULA DEL PROPIETARIO', 'TELÉFONO DEL PROPIETARIO',
       'DIRECCIÓN DEL PROPIETARIO', 'CORREO ELECTRÓNICO',
       'NOMBRE DEL ASISTENTE TÉCNICO', 'CÉDULA  DEL ASISTENTE TÉCNICO',
       'TARJETA PROFESIONAL  DEL ASISTENTE TÉCNICO',
       'TELÉFONO DEL ASISTENTE TÉCNICO', 'OBSERVACIONES '],
      dtype='str')

In [4]:
data_frame.info()

<class 'pandas.DataFrame'>
RangeIndex: 11295 entries, 0 to 11294
Data columns (total 30 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   No.                                         2640 non-null   object
 1   DEPARTAMENTO                                2639 non-null   str
 2   MUNICIPIO                                   2641 non-null   str
 3   VEREDA                                      2608 non-null   str
 4   NOMBRE DEL VIVERO                           2647 non-null   str
 5   LATITUD                                     2485 non-null   object
 6   LONGITUD                                    2485 non-null   object
 7   ALTITUD                                     2285 non-null   object
 8   ESTADO                                      2629 non-null   str
 9   NÚMERO DE REGISTRO OTORGADO                 2532 non-null   object
 10  FECHA DE OTORGAMIENTO DE REGISTRO           2495 non-null   object
 11  VIGENCIA                                    2380 non-null   object
 12  CAPACIDAD DE PRODUCCIÓN plantas/año         1965 non-null   object
 13  FRUTALES                                    1774 non-null   object
 14  CITRICOS                                    720 non-null    object
 15  FORESTALES                                  2956 non-null   object
 16  ORNAMENTALES                                7811 non-null   object
 17  HORTALIZAS                                  332 non-null    object
 18  AROMATICAS Y MEDICINALES                    811 non-null    object
 19  OTRAS ESPECIES                              1132 non-null   object
 20  PROPIETARIO NOMBRE                          2610 non-null   str
 21  NO. CEDULA DEL PROPIETARIO                  2556 non-null   object
 22  TELÉFONO DEL PROPIETARIO                    2591 non-null   object
 23  DIRECCIÓN DEL PROPIETARIO                   2624 non-null   object
 24  CORREO ELECTRÓNICO                          2470 non-null   object
 25  NOMBRE DEL ASISTENTE TÉCNICO                2237 non-null   object
 26  CÉDULA  DEL ASISTENTE TÉCNICO               2174 non-null   object
 27  TARJETA PROFESIONAL  DEL ASISTENTE TÉCNICO  2154 non-null   object
 28  TELÉFONO DEL ASISTENTE TÉCNICO              1851 non-null   object
 29  OBSERVACIONES                               942 non-null    object
dtypes: object(24), str(6)
memory usage: 2.6+ MB

In [5]:
data_frame.isna().sum()

No.                                            8655
DEPARTAMENTO                                   8656
MUNICIPIO                                      8654
VEREDA                                         8687
NOMBRE DEL VIVERO                              8648
LATITUD                                        8810
LONGITUD                                       8810
ALTITUD                                        9010
ESTADO                                         8666
NÚMERO DE REGISTRO OTORGADO                    8763
FECHA DE OTORGAMIENTO DE REGISTRO              8800
VIGENCIA                                       8915
CAPACIDAD DE PRODUCCIÓN plantas/año            9330
FRUTALES                                       9521
CITRICOS                                      10575
FORESTALES                                     8339
ORNAMENTALES                                   3484
HORTALIZAS                                    10963
AROMATICAS Y MEDICINALES                      10484
OTRAS ESPECIES                                10163
PROPIETARIO NOMBRE                             8685
NO. CEDULA DEL PROPIETARIO                     8739
TELÉFONO DEL PROPIETARIO                       8704
DIRECCIÓN DEL PROPIETARIO                      8671
CORREO ELECTRÓNICO                             8825
NOMBRE DEL ASISTENTE TÉCNICO                   9058
CÉDULA  DEL ASISTENTE TÉCNICO                  9121
TARJETA PROFESIONAL  DEL ASISTENTE TÉCNICO     9141
TELÉFONO DEL ASISTENTE TÉCNICO                 9444
OBSERVACIONES                                 10353
dtype: int64

In [6]:
porcentaje = data_frame.isna().mean()*100
print(porcentaje)

No.                                           76.626826
DEPARTAMENTO                                  76.635680
MUNICIPIO                                     76.617973
VEREDA                                        76.910137
NOMBRE DEL VIVERO                             76.564852
LATITUD                                       77.999115
LONGITUD                                      77.999115
ALTITUD                                       79.769810
ESTADO                                        76.724214
NÚMERO DE REGISTRO OTORGADO                   77.583001
FECHA DE OTORGAMIENTO DE REGISTRO             77.910580
VIGENCIA                                      78.928730
CAPACIDAD DE PRODUCCIÓN plantas/año           82.602922
FRUTALES                                      84.293935
CITRICOS                                      93.625498
FORESTALES                                    73.829128
ORNAMENTALES                                  30.845507
HORTALIZAS                                    97.060646
AROMATICAS Y MEDICINALES                      92.819832
OTRAS ESPECIES                                89.977866
PROPIETARIO NOMBRE                            76.892430
NO. CEDULA DEL PROPIETARIO                    77.370518
TELÉFONO DEL PROPIETARIO                      77.060646
DIRECCIÓN DEL PROPIETARIO                     76.768482
CORREO ELECTRÓNICO                            78.131917
NOMBRE DEL ASISTENTE TÉCNICO                  80.194776
CÉDULA  DEL ASISTENTE TÉCNICO                 80.752545
TARJETA PROFESIONAL  DEL ASISTENTE TÉCNICO    80.929615
TELÉFONO DEL ASISTENTE TÉCNICO                83.612218
OBSERVACIONES                                 91.660027
dtype: float64

In [7]:
data_frame.isna().all(axis=1).sum()

np.int64(32)

In [8]:
#data_frame = data_frame.dropna(how='all')

In [9]:
data_frame[data_frame["NOMBRE DEL VIVERO"].isna()]

,No.,DEPARTAMENTO,MUNICIPIO,VEREDA,NOMBRE DEL VIVERO,LATITUD,LONGITUD,ALTITUD,ESTADO,NÚMERO DE REGISTRO OTORGADO,...,PROPIETARIO NOMBRE,NO. CEDULA DEL PROPIETARIO,TELÉFONO DEL PROPIETARIO,DIRECCIÓN DEL PROPIETARIO,CORREO ELECTRÓNICO,NOMBRE DEL ASISTENTE TÉCNICO,CÉDULA DEL ASISTENTE TÉCNICO,TARJETA PROFESIONAL DEL ASISTENTE TÉCNICO,TELÉFONO DEL ASISTENTE TÉCNICO,OBSERVACIONES
229,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
236,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,MULTIACTIVA UNION DE CACAOTEROS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
241,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
242,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
243,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11264,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,441,...,NaN,NaN,3212928430,LOTE BELLAVISTA,NaN,NaN,NaN,NaN,NaN,NaN
11265,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11266,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11278,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11279,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
data_frame.duplicated().sum()

np.int64(713)

In [11]:
duplicados = data_frame[data_frame.duplicated(keep=False)]

In [12]:
duplicados.head()

,No.,DEPARTAMENTO,MUNICIPIO,VEREDA,NOMBRE DEL VIVERO,LATITUD,LONGITUD,ALTITUD,ESTADO,NÚMERO DE REGISTRO OTORGADO,...,PROPIETARIO NOMBRE,NO. CEDULA DEL PROPIETARIO,TELÉFONO DEL PROPIETARIO,DIRECCIÓN DEL PROPIETARIO,CORREO ELECTRÓNICO,NOMBRE DEL ASISTENTE TÉCNICO,CÉDULA DEL ASISTENTE TÉCNICO,TARJETA PROFESIONAL DEL ASISTENTE TÉCNICO,TELÉFONO DEL ASISTENTE TÉCNICO,OBSERVACIONES
242,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
372,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
373,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
374,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
375,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
duplicados.tail

<bound method NDFrame.tail of       No.  DEPARTAMENTO MUNICIPIO VEREDA NOMBRE DEL VIVERO LATITUD LONGITUD  \
242    NaN          NaN       NaN    NaN               NaN     NaN      NaN
372    NaN          NaN       NaN    NaN               NaN     NaN      NaN
373    NaN          NaN       NaN    NaN               NaN     NaN      NaN
374    NaN          NaN       NaN    NaN               NaN     NaN      NaN
375    NaN          NaN       NaN    NaN               NaN     NaN      NaN
...    ...          ...       ...    ...               ...     ...      ...
10890  NaN          NaN       NaN    NaN               NaN     NaN      NaN
11094  NaN          NaN       NaN    NaN               NaN     NaN      NaN
11102  NaN          NaN       NaN    NaN               NaN     NaN      NaN
11125  NaN          NaN       NaN    NaN               NaN     NaN      NaN
11278  NaN          NaN       NaN    NaN               NaN     NaN      NaN

      ALTITUD ESTADO  NÚMERO DE REGISTRO OTORGADO   ... PROPIETARIO NOMBRE  \
242       NaN     NaN                          NaN  ...                NaN
372       NaN     NaN                          NaN  ...                NaN
373       NaN     NaN                          NaN  ...                NaN
374       NaN     NaN                          NaN  ...                NaN
375       NaN     NaN                          NaN  ...                NaN
...       ...     ...                          ...  ...                ...
10890     NaN     NaN                          NaN  ...                NaN
11094     NaN     NaN                          NaN  ...                NaN
11102     NaN     NaN                          NaN  ...                NaN
11125     NaN     NaN                          NaN  ...                NaN
11278     NaN     NaN                          NaN  ...                NaN

      NO. CEDULA DEL PROPIETARIO TELÉFONO DEL PROPIETARIO  \
242                          NaN                      NaN
372                          NaN                      NaN
373                          NaN                      NaN
374                          NaN                      NaN
375                          NaN                      NaN
...                          ...                      ...
10890                        NaN                      NaN
11094                        NaN                      NaN
11102                        NaN                      NaN
11125                        NaN                      NaN
11278                        NaN                      NaN

      DIRECCIÓN DEL PROPIETARIO CORREO ELECTRÓNICO  \
242                         NaN                NaN
372                         NaN                NaN
373                         NaN                NaN
374                         NaN                NaN
375                         NaN                NaN
...                         ...                ...
10890                       NaN                NaN
11094                       NaN                NaN
11102                       NaN                NaN
11125                       NaN                NaN
11278                       NaN                NaN

      NOMBRE DEL ASISTENTE TÉCNICO CÉDULA  DEL ASISTENTE TÉCNICO  \
242                            NaN                           NaN
372                            NaN                           NaN
373                            NaN                           NaN
374                            NaN                           NaN
375                            NaN                           NaN
...                            ...                           ...
10890                          NaN                           NaN
11094                          NaN                           NaN
11102                          NaN                           NaN
11125                          NaN                           NaN
11278                          NaN                           NaN

      TARJETA PROFESIONAL  DEL ASISTENTE TÉCNICO  \
242                                          NaN
372                                          NaN
373                                          NaN
374                                          NaN
375                                          NaN
...                                          ...
10890                                        NaN
11094                                        NaN
11102                                        NaN
11125                                        NaN
11278                                        NaN

      TELÉFONO DEL ASISTENTE TÉCNICO OBSERVACIONES
242                              NaN            NaN
372                              NaN            NaN
373                              NaN            NaN
374                              NaN            NaN
375                              NaN            NaN
...                              ...            ...
10890                            NaN            NaN
11094                            NaN            NaN
11102                            NaN            NaN
11125                            NaN            NaN
11278                            NaN            NaN

[1071 rows x 30 columns]>

In [14]:
duplicados.shape

(1071, 30)

In [15]:
data_frame[data_frame.duplicated(
    subset =["NOMBRE DEL VIVERO"],
    keep=False

)]

,No.,DEPARTAMENTO,MUNICIPIO,VEREDA,NOMBRE DEL VIVERO,LATITUD,LONGITUD,ALTITUD,ESTADO,NÚMERO DE REGISTRO OTORGADO,...,PROPIETARIO NOMBRE,NO. CEDULA DEL PROPIETARIO,TELÉFONO DEL PROPIETARIO,DIRECCIÓN DEL PROPIETARIO,CORREO ELECTRÓNICO,NOMBRE DEL ASISTENTE TÉCNICO,CÉDULA DEL ASISTENTE TÉCNICO,TARJETA PROFESIONAL DEL ASISTENTE TÉCNICO,TELÉFONO DEL ASISTENTE TÉCNICO,OBSERVACIONES
4,4,ANTIOQUIA,Urrao,San Jose - Via Urrao - Betulia Km 7,Plantuladora El Paraiso,6.259529,-76.129879,1876,Registrado,22666,...,Julian Andres Bulla,1055670236,3124521042,Marinilla - Cra 44-B #2915 Conjunto Bariloche,"plantulasparaiso3@hotmail,com",Diego Armando Solano Montenegro,74282972,23935,3104932787,NaN
41,41,ANTIOQUIA,Jardin,El Tapado-Predio El Llano De Jardin,La Palma,5.601324,-75.838434,1682,Registrado,14152,...,Nabor orlando Giraldo Velasquez,70810657-9,3116099504,El Tapado-Predio El Llano De Jardin,novorgiraldo63@hotmai.com,Diego Alexces Granada Celis,71532063,22773 UNA,3217668914,NaN
42,42,ANTIOQUIA,Jardin,El Tapado-Predio El Llano De Jardin,La Palma,5.601324,-75.838434,1682,Registrado,14153,...,Nabor orlando Giraldo Velasquez,70810657-10,3116099504,El Tapado-Predio El Llano De Jardin,novorgiraldo63@hotmai.com,Diego Alexces Granada Celis,71532063,22773 UNA,3217668914,NaN
49,49,ANTIOQUIA,La Ceja,Via La Ceja Rionegro km 3- Municipio La Ceja,Capiro Vivero S.A.S,6.047956,-75.395641,2154,Registrado,20116,...,Carlos Alberto Lopez Alzate,15434082,3186174282,Cra 19 # 21-14,capiroviveroadm@gmail.com,Carlos Andres Gonzalez Gomez,15448182,25939 UCO,,NaN
52,52,ANTIOQUIA,Barbosa,Corregimiento Hatillo - Barbosa Antiqua,Bio Organcos,6.419628,-75.392789,1430,Registrado,21484,...,Esteban Mesa Garcia,8032250,3122588940,Vda San Diego Via Antigua Al Hatillo km5 Barb...,administracion@biorganicos.com.co,Natalia Andrea Garcia Alvarez,1036930201,05121018528 ANT,3013308966,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11266,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11269,1,Vichada,Puerto Carreño,La esmeralda,LAS BONITAS,5.73954,-68.22435,96,REGISTRADO,113157,...,Inversiones forestales de Colombia S.A.S,900600871-8,3102098740,Cra 47#93-20 barrio Castellana- Bogota,juanquintero@inforcol.co,Andres Cordoba Hernandez,71786229,18053,3102359034,NaN
11278,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11279,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11294,24,Vichada,Puerto Carreño,La esmeralda,LAS BONITAS,574081,-6822453,99,REGISTRADO,9001-25,...,Inversiones forestales de Colombia S.A.S,900151686-7,3165376732,calle 26 sur N° 22-27 casa santa ana envigado-...,natalia.quevedo@inverbosques.com,Gabriel Jaime Lopera Arango,15513574,19754,NaN,NaN